[package]
name = "harana-actions-xml"
version.workspace = true
edition.workspace = true

[dependencies]
quick-xml.workspace = true
serde.workspace = true
serde_json.workspace = true

[dev-dependencies]
tokio.workspace = true
