[package]
name = "harana-actions-random"
version.workspace = true
edition.workspace = true

[dependencies]
rand.workspace = true
uuid.workspace = true
serde.workspace = true
serde_json.workspace = true
base64.workspace = true

[dev-dependencies]
tokio.workspace = true
