[package]
name = "harana-actions-geolocation"
version.workspace = true
edition.workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true
geo.workspace = true
chrono.workspace = true
chrono-tz.workspace = true

[dev-dependencies]
tokio.workspace = true
