[package]
name = "harana-actions-secret"
version.workspace = true
edition.workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true
chrono.workspace = true
parking_lot.workspace = true
once_cell.workspace = true
dashmap.workspace = true
uuid.workspace = true
rand.workspace = true
base64.workspace = true

[dev-dependencies]
tokio.workspace = true
