[package]
name = "harana-actions-json"
version.workspace = true
edition.workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true
jsonpath-rust.workspace = true
indexmap.workspace = true

[dev-dependencies]
tokio.workspace = true
