[package]
name = "harana-actions-transform"
version.workspace = true
edition.workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true
serde_yaml.workspace = true
base64.workspace = true
csv.workspace = true
quick-xml.workspace = true
pulldown-cmark.workspace = true
urlencoding.workspace = true
htmlize.workspace = true

[dev-dependencies]
tokio.workspace = true
