[package]
name = "harana-actions-pdf"
version.workspace = true
edition.workspace = true

[dependencies]
lopdf.workspace = true
serde.workspace = true
serde_json.workspace = true
chrono.workspace = true

[dev-dependencies]
tokio.workspace = true
