[package]
name = "harana-actions-image"
version.workspace = true
edition.workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true
image.workspace = true
base64.workspace = true

[dev-dependencies]
tokio.workspace = true
tempfile.workspace = true
