[package]
name = "harana-actions-aws"
version.workspace = true
edition.workspace = true

[dependencies]
aws-config.workspace = true
aws-sdk-acm.workspace = true
aws-sdk-autoscaling.workspace = true
aws-sdk-cloudfront.workspace = true
aws-sdk-ec2.workspace = true
aws-sdk-ecr.workspace = true
aws-sdk-ecs.workspace = true
aws-sdk-elasticloadbalancingv2.workspace = true
aws-sdk-eventbridge.workspace = true
aws-sdk-iam.workspace = true
aws-sdk-lambda.workspace = true
aws-sdk-rds.workspace = true
aws-sdk-route53.workspace = true
aws-sdk-s3.workspace = true
aws-sdk-secretsmanager.workspace = true
aws-sdk-ses.workspace = true
aws-sdk-sqs.workspace = true
aws-sdk-sts.workspace = true
aws-smithy-types.workspace = true
base64.workspace = true
chrono.workspace = true
dashmap.workspace = true
once_cell.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
urlencoding.workspace = true
uuid.workspace = true

[dev-dependencies]
tokio.workspace = true
