[package]
name = "harana-actions-aws-iam"
version.workspace = true
edition.workspace = true

[dependencies]
aws-config.workspace = true
aws-sdk-iam.workspace = true
chrono.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
urlencoding.workspace = true
