[package]
name = "harana-actions-aws-s3"
version.workspace = true
edition.workspace = true

[dependencies]
aws-config.workspace = true
aws-sdk-s3.workspace = true
aws-smithy-types.workspace = true
chrono.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
