[package]
name = "harana-actions-text"
version.workspace = true
edition.workspace = true

[dependencies]
regex.workspace = true
heck.workspace = true
serde.workspace = true
serde_json.workspace = true
minijinja.workspace = true
unicode-segmentation.workspace = true

[dev-dependencies]
tokio.workspace = true
