[package]
name = "harana-actions-cloudflare"
version.workspace = true
edition.workspace = true

[dependencies]
chrono.workspace = true
serde.workspace = true
serde_json.workspace = true
worker = { version = "0.7.4", features = ["axum", "http", "d1", "queue"] }
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
js-sys = "0.3"
serde-wasm-bindgen = "0.6"

[dev-dependencies]
tokio.workspace = true
