[package]
name = "harana-actions-aws-route53"
version.workspace = true
edition.workspace = true

[dependencies]
aws-config.workspace = true
aws-sdk-route53.workspace = true
chrono.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
