[package]
name = "harana-actions-aws-ses"
version.workspace = true
edition.workspace = true

[dependencies]
aws-config.workspace = true
aws-sdk-ses.workspace = true
chrono.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
