[package]
name = "harana-actions-archive"
version.workspace = true
edition.workspace = true

[dependencies]
zip.workspace = true
tar.workspace = true
flate2.workspace = true
serde.workspace = true
serde_json.workspace = true
walkdir.workspace = true
tokio.workspace = true

[dev-dependencies]
tokio.workspace = true
tempfile.workspace = true
