[package]
name = "harana-actions-csv"
version.workspace = true
edition.workspace = true

[dependencies]
csv.workspace = true
serde.workspace = true
serde_json.workspace = true
regex.workspace = true

[dev-dependencies]
tokio.workspace = true
