[package]
name = "harana-actions-excel"
version.workspace = true
edition.workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true
calamine.workspace = true
rust_xlsxwriter.workspace = true

[dev-dependencies]
tokio.workspace = true
tempfile.workspace = true
