name = "harana-server"
main = "build/index.js"
compatibility_date = "2025-01-01"

[build]
command = "cargo install -q worker-build@^0.7 && worker-build --release -- --no-default-features --features cloudflare"
