[package]
name = "harana-actions-markdown"
version.workspace = true
edition.workspace = true

[dependencies]
pulldown-cmark.workspace = true
html2md.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_yaml.workspace = true

[dev-dependencies]
html2md.workspace = true
tokio.workspace = true
