[package]
name = "harana-actions-aws-ecs"
version.workspace = true
edition.workspace = true

[dependencies]
aws-config.workspace = true
aws-sdk-ecs.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
