[package]
name = "harana-actions-http-response"
version.workspace = true
edition.workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true
handlebars.workspace = true
chrono.workspace = true

[dev-dependencies]
tokio.workspace = true
