[package]
name = "harana-actions-passkey"
version.workspace = true
edition.workspace = true

[dependencies]
webauthn-rs.workspace = true
webauthn-rs-proto.workspace = true
url.workspace = true
serde.workspace = true
serde_json.workspace = true
dashmap.workspace = true
parking_lot.workspace = true
once_cell.workspace = true
uuid.workspace = true
chrono.workspace = true
base64.workspace = true

[dev-dependencies]
tokio.workspace = true
