[package]
name = "harana-actions-aws-ec2"
version.workspace = true
edition.workspace = true

[dependencies]
aws-config.workspace = true
aws-sdk-ec2.workspace = true
base64.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
