[package]
name = "harana-actions-html"
version.workspace = true
edition.workspace = true

[dependencies]
scraper.workspace = true
ammonia.workspace = true
serde.workspace = true
serde_json.workspace = true

[dev-dependencies]
tokio.workspace = true
