[package]
name = "harana-actions-url"
version.workspace = true
edition.workspace = true

[dependencies]
url.workspace = true
percent-encoding.workspace = true
serde.workspace = true
serde_json.workspace = true

[dev-dependencies]
tokio.workspace = true
