- object: deploy_netlify
  schema:
    - deploy_message: string? #max(1000)
    - enabled: boolean = true
    - functions_dir: string? #max(2000)
    - production: boolean = true
    - site_id: string #max(200)
    - source_dir: string #max(2000)
    - token_env: string #max(200)
