[package]
name = "harana-actions-healthcheck"
version.workspace = true
edition.workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true
sysinfo.workspace = true
reqwest.workspace = true
tokio.workspace = true

[dev-dependencies]
tokio.workspace = true
wiremock.workspace = true
