[package]
name = "harana-actions-aws-cloudfront"
version.workspace = true
edition.workspace = true

[dependencies]
aws-config.workspace = true
aws-sdk-cloudfront.workspace = true
chrono.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
uuid.workspace = true
